<a href="https://colab.research.google.com/github/rakib181/heisenberg/blob/main/class4_ete_lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr1 = np.random.randint(10,30, size=8)
arr1

array([26, 26, 18, 23, 17, 22, 10, 16])

In [ ]:
arr2 = np.random.randint(20,200,size=50).reshape(5,10)  #method chaining - numbers from 0 to 50
arr2

array([[ 84, 163, 190, 148, 110,  68, 105, 195,  93,  69],
       [188, 177, 183, 183, 134, 154, 132, 126, 102,  96],
       [141,  32, 191, 137,  38,  34, 173, 100, 163,  87],
       [ 34,  80, 122,  78, 175,  24,  76, 116, 152,  55],
       [ 29,  99, 187, 124,  56,  49, 161, 167,  69, 170]])

In [ ]:
arr1[0]

26

In [ ]:
arr1[3]

23

In [ ]:
arr1[:3] #get the first 3 elements. Gets lower bounds inclusive, upper bound exclusive

array([26, 26, 18])

In [ ]:
arr1[2:] #lower bound inclusive

array([18, 23, 17, 22, 10, 16])

In [ ]:
arr1[2:5] #get elements at index 2,3,4

array([18, 23, 17])

In [ ]:
#Show last element
arr1[-1]

16

In [ ]:
#Show all element
arr1[:]

array([26, 26, 18, 23, 17, 22, 10, 16])

In [ ]:
arr2[0,0] #style 1 - you pass in a list of indices

84

In [ ]:
arr2[0][0] #style 2 - parse it as list of lists - not so popular

84

In [ ]:
arr2[1] # get a full row

array([188, 177, 183, 183, 134, 154, 132, 126, 102,  96])

In [ ]:
#get the second column
arr2[:,1]

array([163, 177,  32,  80,  99])

In [ ]:
#get the 3rd row
arr2[2,:] #which is same as arr2[2]

array([141,  32, 191, 137,  38,  34, 173, 100, 163,  87])

In [ ]:
#get the center 3,3 elements - columns 4,5,6 and rows 1,2,3
arr2[1:4, 4:7]

array([[134, 154, 132],
       [ 38,  34, 173],
       [175,  24,  76]])

In [ ]:
arr2_subset = arr2[1:4, 4:7]
arr2_subset

array([[134, 154, 132],
       [ 38,  34, 173],
       [175,  24,  76]])

In [ ]:
arr2_subset[:,:] = 999 #assign this entire numpy the same values
arr2_subset

array([[999, 999, 999],
       [999, 999, 999],
       [999, 999, 999]])

In [ ]:
arr3_subset = arr2_subset.copy()
arr3_subset

array([[999, 999, 999],
       [999, 999, 999],
       [999, 999, 999]])

In [ ]:
#Notice they are different objects in memory. Thus changing arr3_subset will not affect its source
arr3_subset[:,:] = 0.1
arr2_subset

array([[999, 999, 999],
       [999, 999, 999],
       [999, 999, 999]])

In [ ]:
arr1

array([26, 26, 18, 23, 17, 22, 10, 16])

In [ ]:
arr1>15  # gives truth vector

array([ True,  True,  True,  True,  True,  True, False,  True])

In [ ]:
#You can use the Truth vector as an index to search. Get all numbers greater than 15
arr1[arr1 > 15]

array([26, 26, 18, 23, 17, 22, 16])

In [ ]:
arr1[arr1 > 20]

array([26, 26, 23, 22])

In [ ]:
arr1 > 12

array([ True,  True,  True,  True,  True,  True, False,  True])

In [ ]:
arr2[arr2 > 50] #looses the original shape as its impossible to keep the 2D shape

array([ 84, 163, 190, 148, 110,  68, 105, 195,  93,  69, 188, 177, 183,
       183, 999, 999, 999, 126, 102,  96, 141, 191, 137, 999, 999, 999,
       100, 163,  87,  80, 122,  78, 999, 999, 999, 116, 152,  55,  99,
       187, 124,  56, 161, 167,  69, 170])

In [ ]:
arr2[arr2 < 30]

array([29])

In [ ]:
#Compound searching
arr1[(arr1>16) & (arr1<23)]

array([18, 17, 22])

Before writing a loop, look up the function list here
https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs