<a href="https://colab.research.google.com/github/rakib181/heisenberg/blob/main/LinearAlgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
A=np.array([[3,4,6],[8,9,6],[5,8,6]])
A

array([[3, 4, 6],
       [8, 9, 6],
       [5, 8, 6]])

In [6]:
print("\n Rank of Matrix : ",np.linalg.matrix_rank(A))


 Rank of Matrix :  3


In [7]:
print("\n Trace of Matrix : ",np.trace(A))


 Trace of Matrix :  18


In [8]:
print("\n Determinant of A : ",np.linalg.det(A))


 Determinant of A :  59.999999999999986


In [9]:
print("\n Inverse of A : ",np.linalg.inv(A))


 Inverse of A :  [[ 0.1         0.4        -0.5       ]
 [-0.3        -0.2         0.5       ]
 [ 0.31666667 -0.06666667 -0.08333333]]


In [11]:
print("\n Matrix Power Raised By 3 : ",np.linalg.matrix_power(A,3))


 Matrix Power Raised By 3 :  [[1371 1772 1470]
 [2356 3057 2550]
 [2017 2608 2178]]


In [12]:
from numpy import linalg as alg

In [13]:
B=np.array([[2,-4j],[3j,6]])
B

array([[ 2.+0.j, -0.-4.j],
       [ 0.+3.j,  6.+0.j]])

In [15]:
a,b=alg.eigh(B)

In [16]:
print("\n Eighen Value : ",a)


 Eighen Value :  [0.39444872 7.60555128]


In [17]:
print("\n Eighen Vactor : ",b)


 Eighen Vactor :  [[-0.8816746 +0.j         -0.47185793+0.j        ]
 [ 0.        +0.47185793j  0.        -0.8816746j ]]


In [19]:
X=np.diag((4,5,6))

In [20]:
print("\n Diagonal Matrix : ",X)


 Diagonal Matrix :  [[4 0 0]
 [0 5 0]
 [0 0 6]]


In [22]:
e,f=alg.eigh(X)

In [23]:
print("\n Eighen Value : ",e)


 Eighen Value :  [4. 5. 6.]


In [24]:
print("\n Eighen Vactor : ",f)


 Eighen Vactor :  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
products=np.dot(5,6)
products

30

In [26]:
V_a=2+4j
V_b=4-8j

In [28]:
products=np.dot(V_a,V_b)
products

(40+0j)

In [30]:
A=np.array([[2,5,-8],[4,-9,-2],[3,4,5,]])
B=np.array([7,8,9])
Y=np.linalg.inv(A).dot(B)
Y

array([ 2.65145985,  0.29562044, -0.02737226])

In [31]:
A=np.array([[2,5,-8],[4,-9,-2],[3,4,5,]])
B=np.array([7,8,9])
Y=np.linalg.solve(A,B)
Y

array([ 2.65145985,  0.29562044, -0.02737226])