<a href="https://colab.research.google.com/github/rakib181/heisenberg/blob/main/Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

In [18]:
A= np.array([[6, 1, 1],
            [4, -2, 5],
            [2, 8, 7]])

In [10]:
print ("Rank of A :",np.linalg.matrix_rank(A))


Rank of A : 3


In [13]:
print("\nTrace of A : ",np.trace(A))


Trace of A :  11


In [14]:
C=np.linalg.det(A)
C

-306.0

In [15]:
D=np.linalg.inv(A)
D

array([[ 0.17647059, -0.00326797, -0.02287582],
       [ 0.05882353, -0.13071895,  0.08496732],
       [-0.11764706,  0.1503268 ,  0.05228758]])

In [20]:
E=np.linalg.matrix_power(A, 3)
E

array([[336, 162, 228],
       [406, 162, 469],
       [698, 702, 905]])

In [22]:
from numpy import linalg as alg

In [27]:
a= np.array([[1, -2j], [2j, 5]])
a

array([[ 1.+0.j, -0.-2.j],
       [ 0.+2.j,  5.+0.j]])

In [28]:
c,d=alg.eigh(a)
c
d

array([[-0.92387953+0.j        , -0.38268343+0.j        ],
       [ 0.        +0.38268343j,  0.        -0.92387953j]])

In [29]:
a= np.diag((1,2,3))
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [30]:
c,d=alg.eig(a)
c
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
product = np.dot(5,4)
product

20

In [32]:
vector_a=2+3j
vector_b=4+5j

In [33]:
product=np.dot(vector_a,vector_b)
product

(-7+22j)

In [37]:
A= np.array([[4, 3,2],[-2, 2,3],[3, -5,2]])
B= np.array([25, -10, -4])
Z= np.linalg.solve(A,B)
Z

array([ 5.,  3., -2.])

In [38]:
A= np.array([[4, 3,2],[-2, 2,3],[3, -5,2]])
B= np.array([25, -10, -4])
Z= np.linalg.inv(A).dot(B)
Z

array([ 5.,  3., -2.])