<a href="https://colab.research.google.com/github/rakib181/heisenberg/blob/main/NumpyPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
R=[20,30,25,35,45,50,65,75,80,70]
A=np.array(R)
A

array([20, 30, 25, 35, 45, 50, 65, 75, 80, 70])

In [3]:
A.ndim

1

In [4]:
A.shape

(10,)

In [5]:
A.dtype

dtype('int64')

In [6]:
A.size

10

In [7]:
Y=[[25,30],[35,40],[45,50],[55,60],[65,70]]
B=np.array(Y)
B

array([[25, 30],
       [35, 40],
       [45, 50],
       [55, 60],
       [65, 70]])

In [8]:
B.ndim

2

In [9]:
B.size

10

In [10]:
B.shape

(5, 2)

In [11]:
B.dtype

dtype('int64')

In [13]:
C=np.arange(1,200)
C

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [14]:
D=np.arange(1,500,20)
D

array([  1,  21,  41,  61,  81, 101, 121, 141, 161, 181, 201, 221, 241,
       261, 281, 301, 321, 341, 361, 381, 401, 421, 441, 461, 481])

In [15]:
E=np.zeros(20)
E

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [18]:
F=np.zeros((20,10))
F

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
G=np.ones(20)
G

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [22]:
H=np.ones((10,10))
H

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [26]:
I=np.eye(10)
I

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [27]:
J=np.linspace(1,20,25)
J

array([ 1.        ,  1.79166667,  2.58333333,  3.375     ,  4.16666667,
        4.95833333,  5.75      ,  6.54166667,  7.33333333,  8.125     ,
        8.91666667,  9.70833333, 10.5       , 11.29166667, 12.08333333,
       12.875     , 13.66666667, 14.45833333, 15.25      , 16.04166667,
       16.83333333, 17.625     , 18.41666667, 19.20833333, 20.        ])

In [28]:
K=np.random.rand(50)
K

array([0.99976165, 0.89599464, 0.585847  , 0.16224578, 0.19125812,
       0.08510319, 0.50164225, 0.18834471, 0.82249382, 0.57954741,
       0.21803317, 0.66213507, 0.3292665 , 0.420264  , 0.1723233 ,
       0.15412546, 0.32194106, 0.33407396, 0.45304002, 0.19413236,
       0.82975651, 0.1944301 , 0.16986402, 0.81513078, 0.17835754,
       0.35547051, 0.5569219 , 0.53263505, 0.69893873, 0.83781975,
       0.7023023 , 0.5767162 , 0.73658354, 0.16381679, 0.24288757,
       0.84812666, 0.49659809, 0.17981947, 0.38590688, 0.45323895,
       0.11747514, 0.36502145, 0.01256057, 0.64364681, 0.5125815 ,
       0.81930857, 0.73312455, 0.94426429, 0.96879808, 0.72360151])

In [29]:
L=np.random.rand(10,15)
L

array([[0.35500869, 0.22414874, 0.03283713, 0.79167561, 0.0723468 ,
        0.62295424, 0.2504501 , 0.399663  , 0.10733672, 0.60505832,
        0.29475532, 0.90726703, 0.47250986, 0.13013462, 0.27478569],
       [0.88248646, 0.98321951, 0.28598128, 0.26821361, 0.56596878,
        0.0021132 , 0.91732302, 0.29499358, 0.90871668, 0.1359345 ,
        0.42881143, 0.40223612, 0.53994395, 0.04811842, 0.50043148],
       [0.19350036, 0.68778289, 0.49467345, 0.97776921, 0.71376479,
        0.68358534, 0.36629393, 0.07915825, 0.10470031, 0.05223053,
        0.39893475, 0.34172655, 0.32274891, 0.97284799, 0.8391329 ],
       [0.08430333, 0.38586524, 0.54037008, 0.33478714, 0.74074583,
        0.33909612, 0.17007894, 0.99086404, 0.33087508, 0.42566607,
        0.45325777, 0.4393563 , 0.37684784, 0.25535314, 0.37793203],
       [0.56314855, 0.09215269, 0.42201455, 0.82853545, 0.38161934,
        0.10396815, 0.50945434, 0.75011967, 0.62201454, 0.36131433,
        0.77856725, 0.38105509, 0.2692525 , 

In [30]:
M=np.random.randn(10)
M

array([-0.40931118, -0.15896146, -0.69974333, -0.10240674,  0.51732556,
        0.03510571,  1.87454055,  0.8781123 , -1.07635269, -0.24231367])

In [31]:
N=np.random.randn(5,10)
N

array([[-0.98201623,  0.37088343,  0.69814552, -0.82550768,  1.61171144,
        -0.92706672, -0.47777159,  1.47519149, -2.24430453, -0.8719536 ],
       [ 1.21059416,  0.84873094, -0.69830592,  0.03088446, -0.65138731,
         1.658642  , -2.64790739,  0.63446416, -0.25109841, -0.89587096],
       [ 0.19516178, -1.08726017,  0.15879719,  0.77577921,  0.34822155,
         1.94850742,  0.71811737,  0.24694465, -1.74433725,  0.51397267],
       [-0.23442213, -0.33877395,  1.56467464,  0.58548004,  0.65708048,
        -0.11188485,  0.57797702, -0.95480416,  2.11210836, -1.3805552 ],
       [-1.07835583,  2.40937635, -0.8433604 , -0.5871317 ,  0.58075845,
        -1.64830318, -1.28750138, -0.62407869, -0.38443535,  0.6757568 ]])

In [34]:
O=np.random.randint(5,10)
O

7

In [68]:
P=np.random.randint(5,500,36)
P.ndim
P.size

36

In [70]:
P.reshape(4,9)

array([[ 90,  95, 191,  34, 451, 371,  99, 432, 492],
       [493, 489, 333,  67, 171,  14, 211, 250, 135],
       [163, 497, 382, 393, 373, 255, 288, 241, 111],
       [280,  37, 303, 282, 205, 248, 361,  37, 392]])

In [71]:
Q=np.random.randint(1,250,50)
Q

array([131, 157, 129, 101, 208, 193, 107, 180,  29, 121, 186, 140, 108,
        20,  34,  71, 122,  13,   8, 180,  80,  75, 198, 177, 197, 200,
       136, 203, 122,  75, 139,  60, 178,  67, 133,  32, 122,  28,  57,
       191, 199,  27, 228, 212,  60, 144, 187, 114,  37, 105])

In [73]:
Q.max()

228

In [74]:
Q.min()

8

In [75]:
Q.argmax()

42

In [76]:
Q.argmin()

18

In [78]:
A1=np.random.randint(10,50,size=8)
A1

array([41, 28, 32, 38, 45, 12, 41, 20])

In [82]:
A2=np.random.randint(15,25,size=30).reshape(3,10)
A2

array([[20, 20, 15, 22, 16, 18, 17, 17, 24, 24],
       [21, 15, 21, 15, 17, 24, 20, 18, 22, 21],
       [22, 15, 17, 23, 20, 15, 20, 20, 20, 17]])

In [83]:
A1[0]

41

In [84]:
A1[3]

38

In [86]:
A1[:3]

array([41, 28, 32])

In [87]:
A1[2:]

array([32, 38, 45, 12, 41, 20])

In [88]:
A1[2:5]

array([32, 38, 45])

In [89]:
A1[-1]

20

In [90]:
A1[:]

array([41, 28, 32, 38, 45, 12, 41, 20])

In [92]:
A2[0,0]

20

In [94]:
A2[0][0]

20

In [95]:
A2[1]

array([21, 15, 21, 15, 17, 24, 20, 18, 22, 21])

In [97]:
A2[:,1]

array([20, 15, 15])

In [98]:
A2[:,2]

array([15, 21, 17])

In [101]:
A2[0:5,6:8]

array([[17, 17],
       [20, 18],
       [20, 20]])

In [102]:
A2_subset=A2[0:5,6:8]
A2_subset

array([[17, 17],
       [20, 18],
       [20, 20]])

In [103]:
A2_subset[:,:]=222
A2_subset

array([[222, 222],
       [222, 222],
       [222, 222]])

In [106]:
A3_subset=A2_subset.copy()
A3_subset

array([[222, 222],
       [222, 222],
       [222, 222]])

In [108]:
A3_subset[:,:]=0.1
A2_subset

array([[222, 222],
       [222, 222],
       [222, 222]])

In [109]:
A1

array([41, 28, 32, 38, 45, 12, 41, 20])

In [110]:
A1>12

array([ True,  True,  True,  True,  True, False,  True,  True])

In [111]:
A1<20

array([False, False, False, False, False,  True, False, False])

In [112]:
A1[A1>12]

array([41, 28, 32, 38, 45, 41, 20])

In [113]:
A1[A1<20]

array([12])

In [114]:
A1[(A1>12)&(A1<25)]

array([20])