<a href="https://colab.research.google.com/github/rakib181/heisenberg/blob/main/Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [9]:
A1 = np.random.randint(10,30, size=8)
A1

array([20, 10, 28, 17, 14, 19, 14, 21])

Method chaining - numbers from 0-50

In [18]:
A2 = np.random.randint(20,200,size=50).reshape(5,10)  
A2

array([[ 33, 163,  80, 119, 122,  59, 131,  63,  30, 198],
       [176, 179, 194,  25, 161,  93, 148,  83, 163,  91],
       [165,  45,  34,  51,  41, 111, 174,  36,  33,  67],
       [ 26, 190,  52,  35, 194, 107, 190, 175,  40, 118],
       [ 82,  75,  42, 151, 162, 194,  36,  70, 112,  91]])

In [10]:
A1[0]

20

In [11]:
A1[3]

17

Get the first 3 elements. Gets lower bounds inclusive , upper bounds exclusive

In [13]:
arr1[:3] 


array([11, 17, 20])

Lower bounds inclusive

In [14]:
A1[:2]

array([20, 10])

Get the elements at index 2,3,4

In [15]:
A1[2:5]

array([28, 17, 14])

Show last element

In [16]:
A1[-1]

21

Show all elements

In [17]:
A1[:]

array([20, 10, 28, 17, 14, 19, 14, 21])

Style 1 - you pass in a list of indices

In [19]:
A2[0,0]

33

Get a full row

In [20]:
A2[1]

array([176, 179, 194,  25, 161,  93, 148,  83, 163,  91])

Get the second column

In [21]:
A2[:,1]

array([163, 179,  45, 190,  75])

Get the third row

In [22]:
A2[2,:]

array([165,  45,  34,  51,  41, 111, 174,  36,  33,  67])

Get the center 3,3 elements - columns 4,5,6 and rows 1,2,3

In [23]:
A2[1:4,4:7]

array([[161,  93, 148],
       [ 41, 111, 174],
       [194, 107, 190]])

In [24]:
A2_subset=A2[1:4,4:7]
A2_subset

array([[161,  93, 148],
       [ 41, 111, 174],
       [194, 107, 190]])

Assign this entire numpy the same values

In [26]:
A2_subset[:,:]=999
A2_subset

array([[999, 999, 999],
       [999, 999, 999],
       [999, 999, 999]])

In [29]:
A3_subset=A2_subset.copy()
A3_subset

array([[999, 999, 999],
       [999, 999, 999],
       [999, 999, 999]])

Notice they are different objects in memory. Thus changing arr3_subset will not affect its source

In [32]:
A3_subset[:,:] = 0.1
A2_subset

array([[999, 999, 999],
       [999, 999, 999],
       [999, 999, 999]])

In [33]:
A1

array([20, 10, 28, 17, 14, 19, 14, 21])

Gives truth vector

In [34]:
A1>15

array([ True, False,  True,  True, False,  True, False,  True])

You can use the Truth vector as an index to search. Get all numbers greater than 15

In [35]:
A1[A1>15]

array([20, 28, 17, 19, 21])

In [36]:
A1[A1>20]

array([28, 21])

In [37]:
A1>12

array([ True, False,  True,  True,  True,  True,  True,  True])

In [38]:
A2[A2>50]

array([163,  80, 119, 122,  59, 131,  63, 198, 176, 179, 194, 999, 999,
       999,  83, 163,  91, 165,  51, 999, 999, 999,  67, 190,  52, 999,
       999, 999, 175, 118,  82,  75, 151, 162, 194,  70, 112,  91])

In [39]:
A2[A2<30]

array([25, 26])

Compound searching

In [40]:
A1[(A1>16)&(A1<23)]

array([20, 17, 19, 21])